import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import HeaderCt from "@/components/Header/HeaderCt";
import Services from "@/components/Services/Services";
import Exp from "@/components/Exp/Exp";
import Us from "@/components/Us/Us";
import Customers from "@/components/Customers/Customers";
import AppDownload from "@/components/AppDownload/AppDownload";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <HeaderCt />
        <Services />
        <Exp />
        <Us />
        <Customers />
        <AppDownload />
        <Footer />
      </main>
    </>
  );
}
