import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import HeaderCt from "@/components/Header/HeaderCt";
import Services from "@/components/Services/Services";
import Exp from "@/components/Exp/Exp";
import Us from "@/components/Us/Us";
import Customers from "@/components/Customers/Customers";
import AppDownload from "@/components/AppDownload/AppDownload";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <HeaderCt />
        <Services />
        <Exp />
        <Us />
        <Customers />
        <AppDownload />
        <Footer />
      </main>
    </>
  );
}
